export default function Head() {
  return (
    <>
      <title>LIKE LIVROS</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="https://media.graphassets.com/output=format:jpg/resize=width:59,height:59,fit:crop/E3JoNlPkQ1WMyrPDFq8S" />
    </>
  )
}
